name: Backend test workflow
on:
  push:
    branches:
      - 'main'
      - 'bugfix/**'
      - 'chore/**'
      - 'docs/**'
      - 'feature/**'
      - 'hotfix/**'
      - 'release/**'
      - 'test/**'
jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
      - name: Get composer cache directory
        id: composer-cache-2
        run: ls -la
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer --working-dir=backend/ config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer --working-dir=backend/ install \
            --audit \
            --classmap-authoritative \
            --no-interaction \
            --optimize-autoloader \
            --prefer-dist
      - name: Cache files
        uses: actions/cache/save@v4
        with:
          path: backend/
          key: project-files-${{ github.run_id }}
  static-analysis:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
      - name: Restore cached files
        uses: actions/cache/restore@v4
        with:
          path: backend/
          key: project-files-${{ github.run_id }}
      - name: static analysis
        run: php backend/vendor/bin/phpstan --configuration=backend/phpstan.dist.neon
  unit-tests:
    needs: [install]
    runs-on: ubuntu-24.04
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
      - name: Restore cached files
        uses: actions/cache/restore@v4
        with:
          path: backend/
          key: project-files-${{ github.run_id }}
      - name: static analysis
        run: php backend/bin/phpunit --configuration backend/phpunit.xml.dist